### ISSUE TITLE
Yoshi's Story won't go past "Nintendo" screen where Yoshi says Nintendo

### ISSUE THREAD

**Issue by SigmaVirus** [loganmc10/GLupeN64#52] opened 2016-09-09 07:29 UTC
This game won't go past the "Nintendo" screen where Yoshi says Nintendo no matter what settings used, I have tried both dynamic_recompiler and cached_interpreter.

I've configured the GLideN64 core settings to what I usually use in Project64 and it's still the same issue.

I'm on these specs:
i7 4790K @ 4.0GHz
AMD R9 380X 4GB GDDR5
16GB Corsair XMS3 DDR3
Windows 10 Anniversary Update RS1 x64

Yoshi's Story should be compatible with Mupen64Plus and GLideN64 as I've played it before and seen videos of it using this combo.

I'm creating this issue here for now just so it's out in the open, I'm going away for a weeks vacation so I'm not able to test anything during this period.

This needs to be tested further, but on my end at this time, Yoshi's Story is broken on GLupeN64.

**Comment by loganmc10** [comment] 2016-09-09 14:50
I can't reproduce this on Linux (using GLES mode or OpenGL), but I can reproduce this on Android and Windows.

I can't seem to get apitrace working properly on Windows, I'll need to look into that in order to debug this.

**Comment by loganmc10** [comment] 2016-09-09 20:41
I've figured out why this is happening, it's actually the same problem as #23 

I need to figure out a good way to integrate the mupen64plus.ini file, I don't think it's going to be good enough to expect people to know where to copy it (not to mention that is more difficult on Android)

**Comment by loganmc10** [comment] 2016-09-09 21:59
Fixed by 598b441e3844af4841df25f48f35ef09fe97d621

**Closed by loganmc10** 2016-09-09 21:59 UTC

**Comment by SigmaVirus** [comment] 2016-09-10 11:58
Sweet, thanks a lot!
