### ISSUE TITLE
High input lag when Framebuffer Emulation enabled

### ISSUE THREAD

**Issue by Tatsuya79** [loganmc10/GLupeN64#55] opened 2016-09-14 11:53 UTC
In Retroarch you can push P for pause, press a button on your joypad (keep it pressed down), then push K for "next frame" to see how many frames it takes for a core to react to an input command.

I did the test with Super Mario 64 (Japan) (Rev A) (Shindou Edition) as I felt Glupen had a problem:
-libretro Mupen = 2 frames for Mario to jump (with "full framerate" option, Standard gives 3 frames)
-libretro Glupen = 5 frames

Plugin is auto on Mupen. 
That's on win7 x64 i5-3570K Nvidia 770.

**Comment by loganmc10** [comment] 2016-09-14 14:19
Can you test something for me?

Can you set "Enable frame buffer emulation = False":
```
glupen64-EnableFBEmulation = "False"
```
in the core options and re-test?

**Comment by Tatsuya79** [comment] 2016-09-14 14:41
Did that, it reacts at the 1st frame now!
But we lose those effects like the Beetle racing menu and so on.

I was wondering: is there a fullframe option like glide64 for gliden64 that isn't ported yet? (to run games at 50/60fps)

**Comment by loganmc10** [comment] 2016-09-14 14:43
By the way, calculating input lag based on frames isn't the greatest way to do it. You probably notice in Mario 64 (with Framebuffer Emulation enabled), that every 2nd frame nothing happens. Mario 64 ran at 30 FPS, but with Framebuffer Emulation enabled it "dupes" every other frame, thus it looks like the game is running at 60 FPS, but every 2nd frame is just a copy.

With Framebuffer Emulation disabled the game runs at 30 FPS.

What you really care about is **seconds** of input lag, and in order to calculate that you need to know what the FPS is. If a 60 FPS game takes 2 frames to react that is the same as a 30 FPS game taking 1 frame to react (in seconds).

Anyway with all that said, it does seem like there are 1-2 "real" frames that don't react to input with Framebuffer Emulation enabled, I'll look into that.

**Comment by Tatsuya79** [comment] 2016-09-14 15:04
Yes I thought it was something like that.
It's just an indication of how the core deso its buffering and input polling but it's interesting to check for issues.

**Comment by orbea** [comment] 2016-09-14 18:37
Just linking the corresponding GLideN64 issue here.
https://github.com/gonetz/GLideN64/issues/1124

**Comment by loganmc10** [comment] 2016-09-14 19:23
This is an interesting issue, Framebuffer Emulation does add essentially 2 "real" frames of input lag where things are happening.

This is present in mupen64plus+GLideN64 though, so it's not an issue specific to this core, I'll keep it open though. It's not present in mupen64plus-libretro because that core doesn't support Framebuffer Emulation, hence the poor emulation of games like Beetle Adventure Racing.

**Comment by Tatsuya79** [comment] 2016-09-14 21:06
What's the difference between our numbers with Mario 64 then?
We talk about 5 frames to jump on Glupen64 vs 3 frames with stand-alone mupen64plus: is that 60fps frame vs 30 fps frame (16ms vs 32ms per frame) / or is GlupeN64 slower?

That's 80ms base processing lag + everything on top (screen, sync, controller, etc). That's quite something.

I wonder if there is something to do about where the input polling occurs like what Brunnis did with Snes cores here: 
http://libretro.com/forums/showthread.php?t=5428

**Comment by loganmc10** [comment] 2016-09-14 21:20
They are the same, RetroArch just shows you the duplicated frames and mupen64plus does not. They each show 2 unique frames before Mario jumps (with Mario actually jumping on the 3rd unique frame), with RetroArch showing you 2 duplicates.

**Comment by loganmc10** [comment] 2016-09-15 17:17
It's a little hard to convince gonetz that this is an issue. I'm not exactly sure what is causing it, the input polling happens at the same time regardless (main_check_inputs() in main.c)

I assume it might be "showing you what happened 2 frames ago" kind of a problem, like the graphics plugin is rendering based on whatever happened 2 frames ago, as opposed to gathering input at the wrong time, but that is just a wild guess.

**Comment by Tatsuya79** [comment] 2016-09-15 17:48
I'm wild guessing in the same direction. :)
Perhaps it's possible to delay the input polling as close as we can to the framebuffer start when it's ON or something like this (as late as possible).

It can be tried here in Glupen64 (that is emu+plug-in) but maybe Gonetz can't control this on stand-alone Mupen?

**Comment by loganmc10** [comment] 2016-09-15 17:56
You can't delay the input polling, you need to "move up" the rendering.

If the theory is correct (that the rendering is 2 frames behind), then the things you are seeing have already happened, the input has already been taken into account, etc...

What you would actually want to do is the opposite, you want to move up the input polling by 2 frames, so that the input that you give is used 2 frames in the future, which is what you are looking at.

**Comment by loganmc10** [comment] 2016-09-16 16:17
@Tatsuya79 Can you test this with mupen64plus-libretro and angrylion? I get 5 frames of lag just like I do with GLupeN64, so I think it might be correct. I think with Framebuffer Emulation disabled it sort of "unnaturally" works around this, but it might be normal.

**Comment by Tatsuya79** [comment] 2016-09-16 20:44
It gives me 5 frames (or jump at the 3rd "real N64 frames at 30fps").

But is that really comparable? 
I don't think there's more than 100ms lag on the original console.
I wonder if the emulator processing really needs this much time or if it's waiting in between those duplicated frames.

**Comment by loganmc10** [comment] 2016-09-16 20:46
angrylion is basically the "gold standard" of graphics emulation, if that's the way it works there, that's the way it should work with GLideN64.

You could be right, maybe there is something going on in the emulator core that is wrong, but it seems there is nothing wrong with the graphics plugin.

**Comment by mudlord** [comment] 2016-09-19 05:30
Huh. Of course. Gonetz says there is nothing the hell wrong with his stuff. 
Of course. :unamused:

**Comment by SigmaVirus** [comment] 2016-09-19 06:59
Can't say that I really have noticed any input lag at all when I'm playing.
When I press A, Mario jumps and I don't reflect on it further and that's how it's always have worked for me.

**Comment by Tasosgemah** [comment] 2016-09-19 08:51
Just to be clear, this kind of input lag does not exist on the real console.

**Comment by loganmc10** [comment] 2016-09-19 10:27
@mudlord can you prove otherwise? It works the same as angrylion

The input lag (and by the way, I am among those who don't notice it at all) isn't caused by the graphics plugin, and it's present in mupen64plus. It's also present using rsp-hle and rsp-cxd4, so if there is really an issue, it probably lies with mupen64plus-core

**Comment by Tasosgemah** [comment] 2016-09-19 10:52
Mario 64 in Mupen64 core doesn't have nearly as much lag though.

When i played it with GlupeN64 i noticed it immediately. I even use a CRT monitor and there is a very noticeable difference for me. I need to test angrylion and GlideN64 on a standalone emulator to see if there is lag there too.

**Comment by Tasosgemah** [comment] 2016-09-19 11:18
Ok so i was either mistaken before, did something wrong or something changed.

Tested all setups on my CRT monitor and i didn't notice such difference with GlupeN64.

**Comment by SigmaVirus** [comment] 2016-09-19 12:01
I'm also one of those who usually doesn't notice input lag, I've only encountered one extreme case of input lag once during all my years in the emulation scene and it was Donkey Kong Country Returns for Wii through Dolphin.

Can't remember what it was that caused it but it's fixed now since long.

Regarding GLideN64 being the culprit for causing input lag, I don't really know about that.
I mean I've been using GLideN64 in Project64 since last year and never witnessed any input lag.

**Comment by loganmc10** [comment] 2016-09-27 15:43
Just so it's clear: This is reproducible with mupen64plus-libretro + angrylion, it is also reproducible in mupen64plus + GLideN64.

There may be something that can be done in mupen64plus-core that could fix this (but it's also possible that here is nothing to be done). It happens with the dynamic_recompiler or pure_interpreter, it also happens with rsp-hle or rsp-cxd4.

**Closed** 2016-09-27 16:36 UTC
Labels: wontfix
