### ISSUE TITLE
Save file trouble (some saves isn't recognizable in GLupeN64)

### ISSUE THREAD

**Issue by SigmaVirus** [loganmc10/GLupeN64#50] opened 2016-09-09 05:29 UTC
This is questionable but GLupeN64 must handle saves differently than mupen64plus_libretro even though they both produce 290 kb .srm files.

This is the list of the games I own:
007 - GoldenEeye (Europe)
DOOM 64 (Europe)
Legend of Zelda, The - Majora's Mask (Europe)
Legend of Zelda, The - Ocarina of Time - Master Quest (Europe)
Legend of Zelda, The - Ocarina of Time (Europe)
Mario Kart 64 (Europe)
Paper Mario (Europe)
Perfect Dark (Europe)
Star Wars - Shadows of the Empire (Europe)
Super Mario 64 (Europe)
Super Smash Bros (Europe)
Yoshi's Story (Europe)

So originally I started out my Nintendo 64 adventures on Project64, had completed saves for all my games.

Found out about mupen64plus for Libretro eons later and used a tool called pj64tosrm to convert my saves which worked perfectly, 290 kb .srm files all the way.

Now the thing is most of my mupen64plus_libretro saves works in GLupeN64 but some don’t.

These save files work:
007 - GoldenEeye (Europe)
Legend of Zelda, The - Majora's Mask (Europe)
Mario Kart 64 (Europe)
Paper Mario (Europe)
Star Wars - Shadows of the Empire (Europe)
Super Mario 64 (Europe)

These save files don’t work:
Legend of Zelda, The - Ocarina of Time - Master Quest (Europe)
Legend of Zelda, The - Ocarina of Time (Europe)
Perfect Dark (Europe)
Super Smash Bros (Europe)

DOOM 64 (Europe) saves to controller pak and uses passwords and Yoshi's Story (Europe) can’t go past the Nintendo screen so that I can’t answer for.

**Comment by loganmc10** [comment] 2016-09-09 12:26
Can you upload a save state that works in mupen64plus-libretro but not GLupeN64?

**Comment by loganmc10** [comment] 2016-09-09 19:30
I tested saving a game using mupen64plus-libretro (Super Smash Bros USA), and loading it using GLupeN64 and it worked.

Honestly, even though the 2 projects share the same "background", they are different, mupen64plus-libretro uses different dynarec code (for x64) than GLupeN64, so there is no guarantee they will be compatible, they will only continue to diverge since mupen64plus-libretro is planning on writing their own dynarec and a host of others things. It is lucky that the savestates are mostly compatible, but it's not a feature, you can only really expect save states from the same core to work.

You could try opening your "broken" savestates in mupen64plus-libretro and play for a bit and save in a different spot to see if you get lucky, but I'm going to close this as a "won't fix"

**Closed by loganmc10** 2016-09-09 19:30 UTC

**Comment by orbea** [comment] 2016-09-10 05:12
I think SigmaVirus is talking about save files (.srm) not save states? I tested this with orcarina of time and was able to reproduce it where this has worked in the past. I would not expect save states to work, but should the same apply to .srm files?

**Comment by loganmc10** [comment] 2016-09-10 11:53
It might be because GLupeN64 defaults to "memory" for the controller. Ie it acts like every controller has a memory pack, mupen64plus-libretro defaults to "none" I believe

**Comment by SigmaVirus** [comment] 2016-09-10 11:57
@orbea is right, I'm talking about save files (.srm) and not save states.

mupen64plus_libretro and GLupeN64 share the same type of saves, 290 kb .srm files but still it's strange that some saves work but some doesn't.

@loganmc10 

Setting it to "none" in core settings doesn't do anything to solve this, I already tried before I left for vacation and it's still the same.

**Comment by loganmc10** [comment] 2016-09-10 12:01
You Dan attach a non working srm and I can take a look if you'd like. It did seem like save states worked so you could always try making a save state in mupen64plus-libretro then opening that in glupen and exit so it saves an srm from glupen

**Comment by orbea** [comment] 2016-09-10 14:14
I have both mupen64plus-libretro and GLupeN64 set to rumble, before the controller state did not matter for this.

Here are two saves for Orcarina of Time for mupen64plus-libretro and GLupeN64 which do not work with the other core.

GLupeN64: http://ks392457.kimsufi.com/orbea/stuff/games/retroarch/saves/GLupeN64/Zelda%20OoT%2064.srm
mupen64plus-libretro: http://ks392457.kimsufi.com/orbea/stuff/games/retroarch/saves/Mupen64Plus/Zelda%20OoT%2064.srm

**Comment by loganmc10** [comment] 2016-09-10 14:58
@orbea are you sure it used to work for Zelda OoT? That is one of the games that @SigmaVirus says didn't work for him.

**Comment by orbea** [comment] 2016-09-10 16:30
Yea, it worked in the early days of GLupeN64. I have not tested it recently though since I started using the RetroArch option to store saves in core specific directories.

**Comment by loganmc10** [comment] 2016-09-10 16:33
Ok, but regardless, it's still not a "feature", a lot of the code inside mupen64plus-core is different between the 2 projects. You could try making a savestate in mupen64plus-libretro, then loading that state in GLupeN64 and playing until the game saves normally and then try and use that .srm file, but there is still no guarantee.

Saving/loading .srm files works within GLupeN64 as it should.

**Comment by orbea** [comment] 2016-09-11 04:46
Yea, I'm fine with that stance. Maintaining save file or save state compatibility between mupen64plus-libretro and GLupeN64 does not seem like a critical feature to me.

**Comment by SigmaVirus** [comment] 2016-09-11 07:14
So let me get this straight, you can actually use save states from mupen64plus_libretro in GLupeN64?

How is that even possible?

To me it sounds like making a save state in ePSXe and then use it for Mednafen PSX or something.

Anyway, I think I get what you mean though.
I'll make save states from the games that don't work in GLupeN64 with mupen64plus_libretro, the I load the save state and make an in-game save which should work for GLupeN64 afterwards.
