### ISSUE TITLE
Compiling issue on Windows MSYS2

### ISSUE THREAD

**Issue by mudlord** [loganmc10/GLupeN64#3] opened 2016-06-19 04:12 UTC
Having a issue with compiling using msys2.
Problem is related to some headers Gonetz is using, most specifically winlnxdefs.h iirc. Complains about some dynamic link library header not being found (which is found on Unix systems just fine).

**Comment by loganmc10** [comment] 2016-06-19 04:25
Honestly I don't use Windows at all, so I have no way to test it, so I'd be happy to accept pull requests to fix these sorts of things but I don't plan to work on it myself.

**Comment by loganmc10** [comment] 2016-06-19 04:59
If you don't want to use winlnxdefs.h I believe you just need to define "OS_WINDOWS" and it won't use it, but I could be wrong

**Comment by mudlord** [comment] 2016-06-20 01:00
yeah, its something I may have to look into for you.

**Comment by loganmc10** [comment] 2016-09-05 01:30
Closing as a duplicate of #36

**Closed by loganmc10** 2016-09-05 01:30 UTC
