### ISSUE TITLE
Diddy Kong Racing missing items (like balloons)

### ISSUE THREAD

**Issue by tony971** [loganmc10/GLupeN64#68] opened 2016-10-04 00:13 UTC
Not sure if it's a regression in glupen64 or gliden64, but today's commits have turned the menus of Pokemon Stadium 2 (NTSC) wonky.

Windows 10 x64
Intel i5-6300U
Nvidia GTX 940m, 372.90

![splash screen](http://i.imgur.com/gMeVAy2.jpg)
![controllers](http://i.imgur.com/Q3iqs5t.png)

**Comment by loganmc10** [comment] 2016-10-04 04:37
I just tried this on Linux and everything looked OK. Can you try with the latest buildbot version? There probably were a few commits today that broke things

**Comment by loganmc10** [comment] 2016-10-04 14:06
@SigmaVirus are you seeing this on Windows?

**Comment by Awakened0** [comment] 2016-10-04 18:42
Latest Windows builds are pretty bad for Diddy Kong Racing:
![image](https://cloud.githubusercontent.com/assets/4565863/19087602/9e158dde-8a40-11e6-84b1-f4a20cd5fbbf.png)

![image](https://cloud.githubusercontent.com/assets/4565863/19087606/a6de9190-8a40-11e6-849d-5e913860a3ff.png)

I have a build from yesterday where the only problems were missing pickup balloons (could only see shadows) and Super Smash Bros. freezing on the intro.

**Comment by Awakened0** [comment] 2016-10-04 18:47
I think most (maybe all?) games are missing a lot of graphics in the latest Windows build, actually:
![image](https://cloud.githubusercontent.com/assets/4565863/19087779/592e5ccc-8a41-11e6-9920-419f0d3a5ca8.png)

![image](https://cloud.githubusercontent.com/assets/4565863/19087782/5fed9186-8a41-11e6-9b54-47cfaa30bb59.png)

**Comment by tony971** [comment] 2016-10-05 00:49
It appears to be related to depth buffer copy to RDRAM. Disabling fixes the issue.

**Comment by loganmc10** [comment] 2016-10-05 00:56
Really? All these issues? That's surprising. That is disabled by default anyway isn't it?

**Comment by tony971** [comment] 2016-10-05 00:59
I only tested the original one reported.

**Comment by tony971** [comment] 2016-10-05 01:02
I just tried out the other two. They're still valid even with depth buffer copy turned off.

**Comment by orbea** [comment] 2016-10-05 01:12
I am getting very similar issue with my new android phone, Ocarina of Time and GLupeN64 from the libretro build bot. Mupen64plus-ae however works. I don't really know what I'm doing with android yet though so I don't have much more than this yet...

No issues on Slackware with either OpenGL or GLES2.

**Comment by loganmc10** [comment] 2016-10-05 01:24
I'll sort this out tonight hopefully. In the meantime if you could all pray that one day GPU drivers will all work the same and that whoever designed OpenGL will one day burn in a lake of fire that would be helpful.

**Comment by orbea** [comment] 2016-10-05 01:47
Hahah, I'll be praying that that android developers who nerfed fastboot will join them. Its almost full speed and I suspect it would be full speed if I could overclock...

**Comment by Awakened0** [comment] 2016-10-05 02:58
> It appears to be related to depth buffer copy to RDRAM. Disabling fixes the issue.
Having this set to FromMem was what was making Smash Bros. freeze for me. Off or Software work fine.

**Comment by loganmc10** [comment] 2016-10-05 03:16
I don't have immediate access to a Windows machine, but it seems to work properly on Linux, even with VBO's disabled (so it is working the same way as it should on Windows).

Can you guys try deleting your retroarch-core-options.cfg and also disabling Framebuffer Emulation to see if that makes any difference?

**Comment by Awakened0** [comment] 2016-10-05 04:01
> Can you guys try deleting your retroarch-core-options.cfg and also disabling Framebuffer Emulation to see if that makes any difference?

Tried this and it fixed the missing graphics in my previous screenshots. Still can't figure out what's causing the missing balloons in DKR though.

**Comment by loganmc10** [comment] 2016-10-05 04:06
Sorry what fixed the graphics? deleting the config file or disabling framebuffer emulation? Do things work with Framebuffer emulation enabled?

**Comment by Awakened0** [comment] 2016-10-05 04:10
Disabling framebuffer emulation fixed it.

**Comment by loganmc10** [comment] 2016-10-05 13:48
Ok, I can't reproduce this in Linux no matter what I do, so I'll have to wait until tomorrow when I have access to a Windows machine, it's very strange that this is OS specific though.

**Comment by Awakened0** [comment] 2016-10-06 01:29
I wonder if the DKR problem is also Windows only. Since it doesn't happen in the older build I have that doesn't have the framebuffer issue, it might be unrelated to that. I tried turning off the framebuffer and using every "depth buffer copy to RDRAM" option; none of those fix it. Here's what it looks like:

![image](https://cloud.githubusercontent.com/assets/4565863/19137453/fbc262ac-8b41-11e6-98a4-4252b1360cc0.png)

![image](https://cloud.githubusercontent.com/assets/4565863/19137456/066f157e-8b42-11e6-87a4-885c6482e284.png)

Certain sprite based objects like the balloons, bananas and trees aren't showing up. I tried searching through GlideN64 issues to see if there is any mention of this, but didn't see anything.

**Comment by loganmc10** [comment] 2016-10-06 15:11
The only thing I can reproduce is the missing balloons in DKR, everything else works fine for me in Windows (Pokemon Stadium 2, Mario 64, etc...).

The missing balloons also happen on Linux, so it's not Windows specific, I'll check if it happens in mupen64plus as well.

**Comment by loganmc10** [comment] 2016-10-06 15:20
The balloon thing happens with mupen64plus as well, I filed an upstream issue:

https://github.com/gonetz/GLideN64/issues/1159

**Comment by loganmc10** [comment] 2016-10-06 17:52
@tony971 @Awakened0 Do you still have issues in Pokemon Stadium 2 or Mario 64?

If you're having issues other than the missing balloons, can you post your retroarch-core-options.cfg file? I can't reproduce those issues.

**Comment by Awakened0** [comment] 2016-10-06 18:53
Thanks for posting the DKR problem upstream!

I grabbed the latest buildbot build again and still have the missing graphics in Mario 64 if frame buffer emulation is enabled. For reference, I'm on Windows 10 Anniversary with a GTX 970 and the 372.54 drivers. Here are my Glupen core options:

> glupen64-cpucore = "dynamic_recompiler"
glupen64-43screensize = "320x240"
glupen64-169screensize = "320x180"
glupen64-aspect = "4:3"
glupen64-BilinearMode = "3point"
glupen64-EnableFBEmulation = "True"
glupen64-UseNativeResolutionFactor = "0x"
glupen64-EnableCopyAuxiliaryToRDRAM = "True"
glupen64-EnableCopyColorToRDRAM = "Sync"
glupen64-EnableCopyDepthToRDRAM = "Software"
glupen64-EnableCopyColorFromRDRAM = "False"
glupen64-EnableNoise = "True"
glupen64-EnableLOD = "True"
glupen64-EnableHWLighting = "False"
glupen64-CorrectTexrectCoords = "Off"
glupen64-EnableNativeResTexrects = "False"
glupen64-EnableLegacyBlending = "False"
glupen64-EnableFragmentDepthWrite = "True"
glupen64-audio-buffer-size = "2048"
glupen64-astick-deadzone = "15"
glupen64-pak1 = "memory"
glupen64-pak2 = "memory"
glupen64-pak3 = "memory"
glupen64-pak4 = "memory"

**Comment by loganmc10** [comment] 2016-10-06 18:59
I still can't reproduce the issue on Windows with those same settings, can you try disabling EnableCopyAuxiliaryToRDRAM , EnableCopyColorToRDRAM , EnableCopyDepthToRDRAM and see if it's any different? (you need to close and restart the core after changing the options) Those options only work if Framebuffer Emulation is enabled so that's why I'm curious.

**Comment by loganmc10** [comment] 2016-10-06 19:00
Also what version of RetroArch do you use?

**Comment by Awakened0** [comment] 2016-10-06 19:13
Disabling all those options didn't change anything.

My RetroArch's a nightly from 9/22/2016. I tried the latest nightly and there was no difference there either.

**Comment by loganmc10** [comment] 2016-10-06 19:24
Ok one last thing, from your screenshots it looks like you're using a shader, what is the name of it so I can test with that as well?

**Comment by Awakened0** [comment] 2016-10-06 19:42
It's crt-easymode-halation. I tried disabling shaders and that doesn't help.

I also tried setting video_shared_context to "false" in retroarch.cfg, but that just gives me a black screen. Even in the older build.

**Comment by loganmc10** [comment] 2016-10-06 20:07
video_shared_context should be set to false (the default), shaders work for me using the default setting

**Comment by orbea** [comment] 2016-10-06 21:07
Driver issues  maybe? Probably was for me on android, so why not here too?

**Comment by loganmc10** [comment] 2016-10-06 21:14
@Awakened0 can you try the version that is on the buildbot as of right now? (forget the fact that GitHub says there hasn't been a commit in a few hours, I've been shamelessly overwriting the git history...)

**Comment by Awakened0** [comment] 2016-10-06 21:55
Latest build is fixed with framebuffer enabled!

Thanks for all the help.

**Comment by loganmc10** [comment] 2016-10-06 21:59
Ok thanks, I was trying to implement glInvalidateFramebuffer (as described here https://community.arm.com/groups/arm-mali-graphics/blog/2014/04/28/mali-graphics-performance-2-how-to-correctly-handle-framebuffers).

The results were inconsistent across devices to say the least...

**Comment by Awakened0** [comment] 2016-10-06 22:02
I'll note that I still need shared context enabled to use shaders. Even with a single pass shader like pixellate I get a black screen if it's disabled. I had that option enabled for Reicast anyways, so it's not really a problem for me. But since it's off by default if any other user comes across the issue it'd be good to remember :)

**Comment by loganmc10** [comment] 2016-10-07 17:14
@Awakened0 how long has the DKR balloon thing been happening for you? How old is the build that you have where it work properly?

**Comment by loganmc10** [comment] 2016-10-07 18:43
@Awakened0 by the way I just tried 682571636045d4fe3a21635cd63d75072d9986d9 on Windows, which was the first working Windows build, and the problem existed then, are you sure it ever worked for you?

For some reason it works on my Android phone, but not on Windows or Linux (I've just tested inside VMware).

It works for me with mupen64plus on Windows, but not on Linux/VMware. I still need to test mupen64plus+Linux when I get home tonight.

**Comment by orbea** [comment] 2016-10-07 19:24
No issues here on linux still.

**Comment by orbea** [comment] 2016-10-07 19:25
No balloons here either, works with glide64 + mupen64plus though.

**Comment by Awakened0** [comment] 2016-10-07 19:26
The Diddy Kong Racing missing balloon problem was there from the first build of Glupen I tried. It was the frame buffer issue that I didn't have in that first build.

**Comment by loganmc10** [comment] 2016-10-07 19:28
I figured it out, I've updated the upstream issue (https://github.com/gonetz/GLideN64/issues/1159) with the details

**Comment by loganmc10** [comment] 2016-10-07 19:46
Fixed by e6a66df79c0e771cfdb2abf3d6310d217d9dd83a

**Closed by loganmc10** 2016-10-07 19:46 UTC

**Comment by orbea** [comment] 2016-10-08 09:39
This game works well now, I played it a bit bisecting a xdg-screensaver issue in RetroArch.

**Comment by loganmc10** [comment] 2016-12-21 22:10
Hey @Awakened0 do you use Cg or glsl shaders? I'm still confused why you need to use Shared Context to get shaders working

**Comment by Awakened0** [comment] 2016-12-21 23:08
I use CG.

**Comment by loganmc10** [comment] 2016-12-21 23:10
That might be the issue, Cg shaders don't work at all on Linux + GLupeN64.

If you get a chance you should try a glsl shader and see if it works without shared context on, I suspect that is probably the issue.

**Comment by Awakened0** [comment] 2016-12-22 02:02
Yep, I got an xbr glsl shader preset to work fine in Glupen with shared context off.

**Comment by loganmc10** [comment] 2016-12-22 03:12
Ya so it's just a Cg shader thing, I've added a note to the Wiki, https://github.com/loganmc10/GLupeN64/wiki/GPU-Tips
