### ISSUE TITLE
Beetle Adventure Racing crash in menu

### ISSUE THREAD

**Issue by Tasosgemah** [loganmc10/GLupeN64#85] opened 2016-10-24 06:55 UTC
Latest version regression, it was working fine before.

Happens with the latest version. An older version i have works fine.

**Comment by orbea** [comment] 2016-10-24 15:51
I can reproduce this, but it does not occur in upstream GLideN64. It will crash as soon as you press start in the title screen.

OS: `Slackware64-current`
`RetroArch-2016.10.23_31180df_master-x86_64-1_git`
`GLupeN64-2016.10.19_e72887c_master-x86_64-1_git`
```
`Thread 1 "retroarch" received signal SIGSEGV, Segmentation fault.
0x00007fffe9068801 in TextureCache::activateTexture (
    this=0x7fffe97b3a60 <TextureCache::get()::cache>, _t=0, _pTexture=0x0)
    at GLideN64/src/Textures.cpp:1214
warning: Source file is more recent than executable.
1214            glBindTexture(GL_TEXTURE_2D, _pTexture->glName);`
```
gdb log - http://pastebin.com/k3y1tiqP

The first bad commit.
```
95754af8a0aa9c2805a6757a4c300d1f64145604 is the first bad commit
commit 95754af8a0aa9c2805a6757a4c300d1f64145604
Author: Logan McNaughton <logan@bacoosta.com>
Date:   Sat Oct 15 19:44:35 2016 -0600

    Use Renderbuffer on all platforms

:100644 100644 06135b9438f81b1584a513280608133a331f2e9f 7cb2a40ce34b07b23d2f9093abf85dc4538a1322 M	Makefile
```
95754af8a0aa9c2805a6757a4c300d1f64145604

**Comment by loganmc10** [comment] 2016-10-24 17:34
Fix should be in the buildbot now (85e24ce70ac8d19337cb9cced1a490aaaf3c6f1b)

**Comment by orbea** [comment] 2016-10-24 18:54
This is fixed here, thanks.

**Comment by Tasosgemah** [comment] 2016-10-24 20:57
fixed here as well.

**Comment by loganmc10** [comment] 2016-10-28 01:54
Fixed by 34fe33435fb4346304314980d50be578ddfa82c1, this is actually "because" of GLideN64. It is calling glTexParameteri for a texture that doesn't exist, and because GLupeN64 keeps track of GL calls to avoid duplicates it crashes because of a null pointer, so I added a check so that doesn't happen.

**Closed by loganmc10** 2016-10-28 01:54 UTC

**Comment by loganmc10** [comment] 2016-10-28 01:56
By the way @orbea can you check and see if the fog in Beetle Adventure Racing still works for you? In that commit I also changed it to request OpenGL 3.0 instead of 3.3. With the Nvidia proprietary drivers (in Linux and Windows), if you have a card that supports GL 4.+ and you request 3.3, it will give you a 3.3 context, but if you request 3.0 (or 4.0) it gives you the best the card can do (4.5 in my case).

I just want to make sure that the mesa drivers will still request the highest GL context they can when requesting 3.0, a good way to test it is the fog in Beetle Adventure Racing since it requires 4.3+

**Comment by loganmc10** [comment] 2016-10-28 02:19
hm how frustrating, I just tried with Intel Mesa and it behaves the opposite. If you request 3.0 it gives you 3.0, but if you request 3.1 it gives you 3.3 (the highest on my card)...

I guess I'll switch it back so that it supports mesa, since most people on Linux use that, how strange though.
