### ISSUE TITLE
Screen offset in some games.

### ISSUE THREAD

**Issue by orbea** [loganmc10/GLupeN64#16] opened 2016-08-05 04:44 UTC
Mupen64plus-libretro's gln64, rice and angrylion has this same issue with and without `GLIDEN64=1`, however glide64 doesn't.

Its easy to test with Zelda: Orcarina of TIme as it happens in the first few seconds, Mario Kart 64 also shows it. It doesn't always persist, but it does a little during races in Mario Kart.

![1](http://ks392457.kimsufi.com/orbea/stuff/pics/scrots/libretro/mupen64plus/2016-08-04-212903_1680x1050_scrot.png)
![2](http://ks392457.kimsufi.com/orbea/stuff/pics/scrots/libretro/mupen64plus/2016-08-04-212153_1680x1050_scrot.png)
![3](http://ks392457.kimsufi.com/orbea/stuff/pics/scrots/libretro/mupen64plus/2016-08-04-212217_1680x1050_scrot.png)
![4](http://ks392457.kimsufi.com/orbea/stuff/pics/scrots/libretro/mupen64plus/2016-08-04-212204_1680x1050_scrot.png)

**Comment by loganmc10** [comment] 2016-08-05 20:57
Are you referring to the "little bar" on the right of the screen? Can you reproduce this on regular mupen64plus? The intro to OoT looks identical to me using mupen64plus+GLideN64 and GLupeN64

**Comment by orbea** [comment] 2016-08-05 21:52
Yes, I mean the "little bar" along the right and bottom of the screen. The last image shows it well as it should be all black.

I can not test regular mupen64plus because it crashes xorg for me...

**Comment by loganmc10** [comment] 2016-08-05 22:01
Ya I've noticed that in regular mupen64plus and GLideN64, I'll make sure there is no difference between mupen64plus and GLupeN64, if there is no difference I'll close this ticket, since it is an upstream (GLideN64) issue

**Comment by loganmc10** [comment] 2016-08-05 22:14
Ya this is an upstream issue, happens with GLideN64 on mupen64plus as well

**Comment by orbea** [comment] 2016-08-05 23:58
Is there an upstream issue report for it? I would make one, but that does not feel right when I can't even get into a game with it.

**Comment by loganmc10** [comment] 2016-08-06 00:12
I'm not sure, you'd have to browse through the issues on GLideN64 and see if anyone has reported it

**Comment by loganmc10** [comment] 2016-08-06 00:18
There are couple options in GLideN64 that might fix these issues (but are disabled by default because they hurt performance)

CorrectTexrectCoords
enableNativeResTexrects

Unfortunately there is no mechanism currently to enable these options, I'll add them soon. I'll reopen this until they are added

**Comment by loganmc10** [comment] 2016-08-06 02:21
Ok I implemented those options. They don't seem to make any difference in the OoT opening, but you can give them a try (retroarch core options)

**Closed by loganmc10** 2016-08-06 02:21 UTC

**Comment by orbea** [comment] 2016-08-06 04:02
No difference with OoT or Mario Kart.  However `enableNativeResTexrects` fixed black lines in the Nintendo logo for OoT and the player selection screen when using higher resolutions.

**Comment by loganmc10** [comment] 2016-08-29 13:23
I believe this screen offset issue has just been fixed in GLideN64:

https://github.com/gonetz/GLideN64/commit/4c226bcc952a5f7084795a17bf30dce1d654e689

I haven't tested it or merged it into this repo yet, but it sounds like the same problem based on the description in the commit

**Comment by orbea** [comment] 2016-09-13 07:22
Yea, this has been fixed. A few other Mario Kart graphical glitches are fixed now too.
